# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('PC', 'Placement_Cell'), ('TC', 'Training_Cell'), ('ST', 'Student')], default='ST', max_length=2),
        ),
    ]
