# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='Duration of exam')),
                ('times', models.DateField(verbose_name='Date of exam')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='testno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Tests'),
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Question'),
        ),
    ]
