# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170204_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_text',
            field=models.CharField(default='why are you now?', max_length=40),
        ),
    ]
