# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_tests_test_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tests',
            name='times',
            field=models.DateTimeField(verbose_name='Date of exam'),
        ),
    ]
