# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20170204_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crctans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Question')),
            ],
        ),
    ]
