# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
