# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_tests_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tests',
            name='score',
        ),
        migrations.AddField(
            model_name='testscore',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Tests'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
