# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_compilerquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerquestion',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
